services:
  nodered:
    volumes:
      - ./data/nodered:/data
      - /etc/localtime:/etc/localtime
    devices:
      - /dev/vcio:/dev/vcio
    environment:
      - TZ=Europe/Berlin
      - LD_LIBRARY_PATH=/opt/vc/lib
