version: '3.3'

services:

  appdaemon:
    container_name: appdaemon
    restart: always
    image: acockburn/appdaemon:latest
    environment:
      HA_URL: http://${SERVER_IP}:8123
      TOKEN: ${HA_TOKEN}
      DASH_URL: http://${SERVER_IP}:5050
    ports:
      - "5050:5050"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/homeassistant/config/appdaemon:/conf
      - /var/run/dbus:/var/run/dbus #This is only needed if wanting to use Bluetooth, can delete otherwise
    depends_on:
      - homeassistant


  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: always
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./data/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mqtt
      - nodered
#    privileged: true
    network_mode: host

  nodered:
    image: ghcr.io/moeb98/moe-smart-home
    volumes:
      - ./data/nodered:/data
      - /etc/localtime:/etc/localtime
    depends_on:
      - mqtt
    restart: always
    network_mode: "host"
    environment:
      - TZ=Europe/Berlin
    
  mqtt:
    image: "eclipse-mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./data/mqtt:/mosquitto
      - /etc/localtime:/etc/localtime
    restart: always
    environment:
      - TZ=Europe/Berlin
    
  zigbee:
    image: koenkk/zigbee2mqtt
    volumes:
      - ./data/zigbee:/app/data
      - /run/udev:/run/udev:ro
      - /etc/localtime:/etc/localtime
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/ttyACM1:/dev/ttyACM1"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    restart: always
    privileged: true
    ports:
      - 1881:1881
    environment:
      - TZ=Europe/Berlin
