version: '3.8'

services:
  nodered:
    volumes:
      - ./data/nodered:/data
      - /etc/localtime:/etc/localtime
    devices:
      - /dev/vchiq:/dev/vchiq
    environment:
      - TZ=Europe/Berlin
      - LD_LIBRARY_PATH=/opt/vc/lib    
