name: Build Release

on:
  workflow_dispatch:
  release:
    types: [published]
  schedule:
    - cron: "0 10 1 * *" # Update the image every first day of a month at 10am to provide regular updates
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
#    strategy:
#      matrix:
#        node_version: [10, 12, 14]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout latest release
        run: git checkout $(git describe --tags `git rev-list --tags --max-count=1`) -b latest-release
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}
          registry: ghcr.io
      - name: Cache Docker layers
        uses: actions/cache@v4
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -o type=registry \
            -t mrmoe/moe-smart-home:$(git describe --tags `git rev-list --tags --max-count=1`)-amd64 \
            -t mrmoe/moe-smart-home:latest-amd64 \
            -t ghcr.io/moeb98/moe-smart-home:$(git describe --tags `git rev-list --tags --max-count=1`)-amd64 \
            -t ghcr.io/moeb98/moe-smart-home:latest-amd64 \
            --build-arg NODE_RED_VERSION=latest \
            --build-arg OS=alpine \
            --build-arg BUILD_DATE="$(date +"%Y-%m-%dT%H:%M:%SZ")" \
            --build-arg TAG_SUFFIX=latest-amd64 \
            --file ./docker-image/Dockerfile ./docker-image

          docker buildx build \
            --platform linux/arm/v7,linux/arm64,linux/arm/v6 \
            -o type=registry \
            -t mrmoe/moe-smart-home:$(git describe --tags `git rev-list --tags --max-count=1`) \
            -t mrmoe/moe-smart-home:latest \
            -t ghcr.io/moeb98/moe-smart-home:$(git describe --tags `git rev-list --tags --max-count=1`) \
            -t ghcr.io/moeb98/moe-smart-home:latest \
            --build-arg NODE_VERSION=14 \
            --build-arg NODE_RED_VERSION=latest \
            --build-arg OS=alpine \
            --build-arg BUILD_DATE="$(date +"%Y-%m-%dT%H:%M:%SZ")" \
            --build-arg TAG_SUFFIX=latest \
            --file ./docker-image/Dockerfile.arm ./docker-image

